FROM ubuntu:22.04
ENV PATH /app/node_modules/.bin:$PATH

RUN apt-get update && \
  apt install -y  build-essential python-is-python3 git jq wget curl nano openssh-server ngrep tmux net-tools screen vim

RUN curl -sL https://deb.nodesource.com/setup_18.x -o nodesource_setup.sh && \
  bash nodesource_setup.sh && \
  apt install -y nodejs && \
  npm config set prefix ~/.local && \
  echo "PATH=~/.local/bin/:\$PATH" >> ~/.bashrc

RUN echo next
#RUN git clone https://github.com/iamahmedshahh/mm2v3 /app
RUN git clone -b bugfix/rm-scss-utility-classes  https://github.com/imylomylo/mm2v3 /app
WORKDIR /app
#RUN cd /app && npm update
RUN cd /app && npm install
#RUN npm config set unsafe-perm true
#RUN npm install @vue/cli@3.7.0 -g

##COPY start-webapp.sh /usr/local/bin/entrypoint.sh
##CMD ["/usr/local/bin/entrypoint.sh"]
CMD ["npm", "run", "host"]
#CMD ["/bin/bash"]
