FROM ubuntu:18.04
ENV PATH /app/node_modules/.bin:$PATH

RUN apt-get update && \
  apt install -y  build-essential python-dev git jq wget curl nano openssh-server ngrep tmux net-tools screen vim

RUN curl -sL https://deb.nodesource.com/setup_14.x -o nodesource_setup.sh && \
  bash nodesource_setup.sh && \
  apt install -y nodejs && \
  npm config set prefix ~/.local && \
  echo "PATH=~/.local/bin/:\$PATH" >> ~/.bashrc

RUN git clone https://github.com/imylomylo/dev-mm2-web /app
WORKDIR /app
RUN cd /app && npm install
RUN npm config set unsafe-perm true
RUN npm install @vue/cli@3.7.0 -g

#COPY start-webapp.sh /usr/local/bin/entrypoint.sh
#CMD ["/usr/local/bin/entrypoint.sh"]
CMD ["npm", "run", "serve"]
#CMD ["/bin/bash"]
